app/models/article.rb
spec/models/article_spec.rb

Heard about this project on Ruby5. Thanks for open-sourcing it, @olivierlacan! 
I noticed some not-so-truthful comments in `Article` so I thought I'd contribute...
**Changes:**
- `beginning_of_day` consideration removed from `.fresh` and `.stale` scopes. This did not seem to break any tests and removing them eliminates complexity around time and makes it easier to test.
- specs for `#archive?`, `#fresh?`,  `#stale?`, and `#rotten?` were rewritten to be more thorough and to remove dependency on persistence and factories.
- implementation for `#archive?`, `#fresh?`,  `#stale?`, and `#rotten?` refactored for readability.
- rotten or rot-prone comments were removed in favor of more readable code.
btw, tests on `master` were breaking when I pulled, but all green tests are still green locally …

Refactors Article statuses and their tests

---

Gemfile
Gemfile.lock
app/controllers/articles_controller.rb
app/models/article.rb
config/initializers/friendly_id.rb
db/migrate/20150416104151_create_friendly_id_slugs.rb
db/structure.sql

Two related changes of note:
- in ArticlesController, the new respond_with_article_or_redirect method
will redirect to the article_path based on the current slug in case the request
asked for an old slug and return a 301 moved permanently status code
- in the migration, we call save! on all articles in order to trigger the
creation of a FriendlyId
Addresses #127

Replace ad-hoc slugs with FriendlyId

---

Gemfile

The dotenv gem is required in production and should be in the correct place int he Gemfile

dotenv should not be in the development group

---

app.json

The Heroku button isn't working currently due to an invalid plan for the `logentries` addon:
Tested locally and found that the "TryIt" plan should be referenced by `le_tryit` instead of just `tryit`...

Fix logentries addon for Heroku button

---

app/views/articles/_article.html.haml
app/views/authors/show.html.haml
app/views/tags/show.html.haml

The `unless .empty?` checks would load the associations into objects, even if we didn't need them, whereas using `if .any?` will use the `.size` of the loaded record array if available, or issue a COUNT query to the database instead.
Sorry I didn't get back to this for so long! This is my newer, better thought-out solution to #148.

Switch to .any? for checking if has_many associations have records

---

app/models/article.rb
app/views/articles/_form.html.haml
app/views/articles/new.html.haml
spec/models/article_search_spec.rb

Validates there's a title present, an article without a title can't be selected from the listing therefore it is hard to edit.
Also allows you to pick an author for an article (useful when migrating from another wiki). Defaults the author to the currently logged in user.

Validate title and show/select author.

---

app/models/article.rb
app/models/articles_tag.rb
app/models/tag.rb
db/migrate/20150829203748_add_id_to_articles_tags.rb
db/structure.sql

This attempts to clean up some of the `Article` and `Tag` code by refactoring the manual increment/decrement of `tags_count` and `article_count` to use auto-magic from rails.
It changes the relationships between those models to use `has_many :through` relationships to a new model, `ArticlesTag`, and moves the tag uniqueness to validations on `Tag` and `ArticlesTag`.
The long commit messages can tell you even more!
I wasn't sure if the `validates_tag` and `validates_article` were needed, so I removed them. I can add them back if needed.

Automatic counter caches using has_many :through

---

config/initializers/omniauth.rb
spec/models/article_search_spec.rb

This is a function of omniauth/google's API which is poorly documented and probably required for 100% of the private wikis.

Allow restrictions to login by specific domain.

---

app/models/tag.rb
app/views/tags/index.html.haml

More efficient to pull counts from the counter cache than to pull in AR objects just to count them.

Using counter cache column over building AR objects

---

app/models/article.rb

Since there is no passing of zone to #in_time_zone it appears that it is
not necessary here

Using Time.current over #in_time_zone

---

app/assets/stylesheets/foundation/_config.sass
app/assets/stylesheets/structures/_article.sass
app/helpers/application_helper.rb
spec/helpers/application_helper_spec.rb

Finally tackles a long standing problem with outdated links described
in #82.
Since we now have article slug history trackling (if you rename
an article, its original slug & title will still take you to it) this feature
is ready for prime time.
It's now possible to link to any article either via its full title or its slug:
```markdown
[[This is an article title]]
[[this-is-an-article-slug]]
```
This is especially convenient because it takes domains and paths
out of the equation.
However, I'll need to make a rake task to migrate existing URLs that
match valid article titles and hardcode the `ORIENTATION_DOMAIN`
or use relative paths.

Smart (relative) links based on article title or slug

---

app/controllers/articles_controller.rb

Grab the slug and titleize it to extract a potential title and
encourage people to write articles that don't already exists.
This makes sense now that it's unlikely that 404 will happen due to
oudated slugs since we retain slug history and redirection of old
slugs to new ones through FriendlyId.

Redirect to articles#new on 404

---

app/models/article.rb

This logic is causing new slugs to be generated way more times than
necessary.

FriendlyId regeneration logic adjustment

---

app/models/article.rb

Reverts orientation/orientation#167
@mattpolito The code you added is causing @article.slug to be `nil` [in this method](https://github.com/orientation/orientation/blob/master/app/controllers/articles_controller.rb#L171), which is what causes the routing error because `Article#to_param` returns `slug` and we need it to be generated before redirection.
I managed to reproduce this by cleaning up the article feature spec. I'll push that so you can too.

Revert "FriendlyId regeneration logic adjustment"

---

app/controllers/articles_controller.rb
app/decorators/article_decorator.rb
app/jobs/send_article_rotten_job.rb
app/mailers/article_mailer.rb
app/models/article.rb
app/views/articles/show.html.haml
db/migrate/20150922194413_add_rot_reporter_id_to_articles.rb
db/structure.sql
spec/jobs/send_article_rotten_job_spec.rb
spec/jobs/send_article_update_job_spec.rb
spec/mailers/article_mailer_spec.rb
spec/models/article_spec.rb

Now when someone reports an article as rotten we log who it was.
Why?
- it makes things more human, it's not just a game of whack-a-mole to
find articles and mark them as rotten
- it allows for conversations to happen between the reporter and the
article contributors
- if notifications are turned off it allows a reader or contributor of the
article to reach out to the rot reporter in order to refresh the article
This commit also refactors the ArticleRottenJob to put all the fetching
logic inside of it. We don't pass a contributors object, or an article, or
a reporter. All of those are fetched at job runtime.
I'll have to update the Mandrill templates in order to use the now
added REPORTER_NAME and REPORTER_URL merge vars.
Fixes #178

Log rot reporter & mention them in notification

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/articles_controller.rb
app/models/article.rb
config/locales/responders.en.yml
spec/features/creating_an_article_spec.rb
spec/features/updating_an_article_spec.rb
spec/features/viewing_an_article_spec.rb

Added integration specs for article CRUD. 
We needed to delete that 'sign in' flash from the application controller because it was overriding all the other flash messages in development.  
We added the launchy gem for capybara's save_and_open_page.  
We went ahead and removed the redirect logic from the create and update actions. Neither action was redirecting correctly or showing a flash message. Let us know if there is a use case we are missing here

Add content validation and crud specs for articles

---

app/jobs/send_article_update_job.rb
app/mailers/article_mailer.rb
spec/mailers/article_mailer_spec.rb

This helps the team understands who's doing the work of upading articles
and naturally creates communication bridges to topic-experts.

Display editors in article update notifications

---

app.json

JSON objects cannot have trailing commas, so the object was invalid as
written. This prevents the "Deploy to Heroku" button from working.
Removing this comma makes the `app.json` file pass validation and should
fix the "Deploy to Heroku" functionality.

Fix Deploy to Heroku by making app.json valid JSON

---

Gemfile
Gemfile.lock

Hi @olivierlacan, just a small contrib to avoid those warnings on latest bundler:
> The git source `git://github.com/olivierlacan/simple_form.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.

Force HTTPS for GitHub

---

app/models/tag.rb

- Currently behaviour prevents adding a new tag if there are any results returned
- This pull request allows creation of a new tag if it doesn't exist
**Old Behaviour**
**New Behaviour**

Allow Tag creation on partial match

---

app/controllers/tags_controller.rb
app/models/tag.rb
app/views/tags/_form.html.haml
app/views/tags/edit.html.haml
app/views/tags/new.html.haml
app/views/tags/show.html.haml
spec/features/creating_a_tag_spec.rb
spec/features/deleting_a_tag_spec.rb
spec/features/updating_a_tag_spec.rb

- Current version does not allow editing or deletion of tags
- Added the ability to do so with similar flow that exists for articles
**Edit & delete buttons in the tag show page**
**Edit tag page**

Allow editing and deletion of a tag

---

app/controllers/tags_controller.rb
app/views/tags/show.html.haml

These changes only decorate the current (unarchived) articles, lest we start coloring and sorting irrelevant information. A front-end person may want to take a look and modify appropriately.
As always, open to feedback.

Split Archived Articles in Tag Listing

---

.env.example
app/controllers/open_search/descriptions_controller.rb
app/helpers/open_search/descriptions_helper.rb
app/views/layouts/application.html.haml
app/views/open_search/descriptions/show.osd_xml.builder
config/initializers/mime_types.rb
config/routes.rb
spec/controllers/open_search/descriptions_controller_spec.rb

We use Orientation [at Doximity](https://engineering.doximity.com/) for our internal wiki and I wanted to make searching the wiki a little bit easier for our quarterly Hack Day.
This adds OpenSearch specs to Orientation so when you're in Chrome you can type "orien..." and it will suggest "Press [tab] to search Orientation". After hitting tab, typing a search query and hitting enter will direct you to `/articles/search?search=...`.
Here's some screenshots from Chrome locally:
Suggestion:
Tabbed:
Hit enter:
You can control the text in the search box via the `$APP_NAME` environment variable. E.g. we set ours to "Doximity Wiki".

Add OpenSearch specs

---

.env.example
Gemfile
Gemfile.lock
NEWS.md
config/environments/production.rb

It's no longer needed and the gem author has deprecated it.

Remove lets-encrypt-heroku gem

---

Gemfile.lock

That. Unlikely to be exploitable for this repo, but still good practice.

Bump sprockets and nokogiri to remove vulnerabilities

---

Brewfile
Gemfile
Gemfile.lock
README.md
app/assets/stylesheets/structures/_markdown.sass
app/assets/stylesheets/vendor/_highlight.scss
app/helpers/application_helper.rb
app/helpers/html_with_rouge.rb

Long time coming but now that Pygments.rb is barely maintained, that it depends
on a very old version of Python (2.7) and complicates the installation process
for Orientation, it was about time to switch to the most excellent all-Ruby
alternative: http://rouge.jneen.net
I can't believe how easy it was to switch over. Rouge even aliases `shell`
to `bash` and vice-versa which makes the lexer hack I had with Pygments
unnecessary (it would blow up on languages it didn't know).
Rouge on the contrary just doesn't do any highlighting for any language passed
in the Markdown fenced codeblocks that it can't recognize (triple backticks
followed by the language name in lowercase)
What a relief!
Oh, and I took the opportunity to refresh the CSS we're using to display
highlighted code to switch to the …

Replace Pygments.rb with Rouge
