orientation/orientation

- .buildpacks
- app.json
Removing .buildpacks file
Adding in buildpack definition directly into app.json for new officially supported multi-buildpack.
> updating app.json to use the new multi buildpack definition 

- DOCKER.md
- Dockerfile
- config/database.docker.yml
WIP to fix #116:
* created the Dockerfile
* added a `database.docker.yml` template specific to Docker using the [Docker-Compose convention](https://docs.docker.com/compose/env/) for environment variables
* ensure CarrierWave defaults to file storage when S3 credentials are missing
> Docker build

- Gemfile.lock
See:
- https://github.com/rubysec/ruby-advisory-db/blob/master/gems/uglifier/OSVDB-126747.yml
- https://zyan.scripts.mit.edu/blog/backdooring-js/
> Uglifier security update

- app/views/articles/show.html.haml
- spec/models/article_search_spec.rb
Confirms article delete and archive buttons.
> Confirms article delete and archive buttons.

- .gitignore
Allow devs to use gemset if they'd like
> Ignore ruby gemset file

- spec/rails_helper.rb
- spec/support/omniauth.rb
* Clean up spec helper a bit
* Speed up suite by preventing so many AR records from being created.
> Spec updates

- app/controllers/tags_controller.rb
- app/models/article.rb
- app/models/tag.rb
- config/initializers/friendly_id.rb
> FriendlyId slugs for Tags

- app/models/article.rb
- app/models/tag.rb
- app/models/user.rb
A few updates to ActiveRecord calls to improve queries or remove SQL fragments
> AR updates

- app/jobs/send_article_endorsement_job.rb
- app/jobs/send_article_rotten_job.rb
- app/jobs/send_article_update_job.rb
- app/jobs/staleness_notification_job.rb
- app/models/article.rb
- app/models/article_endorsement.rb
- app/models/article_subscription.rb
- app/models/user.rb
- config/application.rb
- spec/jobs/send_article_update_job_spec.rb
- spec/models/article_subscription_spec.rb
Conforming DJ to the ActiveJob interface
> Utilize ActiveJob interface

- app/views/tags/index.html.haml
This fixes the duplicate tag at the bottom of first column and beginning of second column.
Not excited about the code but it fixes the problem for now.
> Tag column adjustment

- app/models/article.rb
- spec/models/article_spec.rb
Hey Olivier, this should fix that low-hanging fruit! #186
> Don't notify article's last editor when the article is updated

- app/controllers/articles_controller.rb
- app/models/article.rb
- spec/features/creating_an_article_spec.rb
- spec/models/article_spec.rb
> Create subscription for author when article is created

- app/helpers/html_with_pygments.rb
https://github.com/orientation/orientation/issues/200
> Don't assume URI can parse everything.

- app/helpers/html_with_pygments.rb
Just a small refactor of a method introduced in #202
> Refactor the safe_url_parser method to be a little simpler

- app/controllers/application_controller.rb
Method does not need one exit, this give a clean escape immediately
> Refactor to use guard clause

- app/decorators/article_decorator.rb
- spec/decorators/article_decorator_spec.rb
> Add specs and refactor ArticleDecorator#authors

- app/models/article.rb
Resolves #188, unless you think simply "Updated within the last __" would be better (or something else). Perhaps "Changed" or "Modified" would cover both cases more succinctly.
This is possibly my first pull request for a project not directly related to my work. Decided to start small. I love the low-hanging-fruit tag! Open to any feedback.
> Change fresh article tooltip to include recently updated articles.

- README.md
Making recommendations for updates to the `README.md`.
I'm not a super experienced Rails dev, and found the `README.md` and installation a bit tricky. I liked that installation was explained basically as:
> Almost one step: rake orientation:install
But in actuality, a bit more was needed that went unexplained (which is probably fine for experienced devs, but like I mentioned, took some debugging and experimenting to figure out).
Also, made a few small grammar and link updates.
> update readme. update install steps.

- .env.example
- app/mailers/article_mailer.rb
- config/initializers/slack.rb
- spec/mailers/article_mailer_spec.rb
Another small contrib, enabling easy FROM customisation.
> Enabling FROM customisation

- package.json
NOTE: package.json only contains frontend assets at this point
> ci(node): Remove node version specification

- README.md
- bin/setup
- lib/tasks/orientation.rake
Ran into a little bit of friction getting the project up-and-running on a fresh machine with an older version of Ruby. Updated the README and setup script to reduce the overhead.
> Update setup instructions for fresh project

- Gemfile.lock
See: https://github.com/flavorjones/loofah/issues/154
> Bump vulnerable version of Loofah to fixed 2.2.3
